In [1]:
import numpy as np

In [2]:
epsilon=10**-2
lr= 10**-2
X=np.array([1,2,3])
X=X.reshape(-1,1)
t=np.array([0.1,0.3,0.7])
t=t.reshape(-1,1)
W=np.matrix('0.5,0.3,0.1; 0.3,0.2,0.1')
Z=np.matrix('0.1,0.2; 0.3,0.4;0.5,0.6')


In [3]:
f=lambda x:1/(1+np.exp(-x))
f_vec = np.vectorize(f)

In [4]:
def forward_propagation_1layer(X,W,Z,f,t):
    b=np.dot(W,X)
    h= f_vec(b)
    a=np.dot(Z,h)
    o=f_vec(a)
    e=np.subtract(t,o)
    print(e.shape)
    return(b,e,o,t,h)

    

In [5]:
def backpropagation_1layer(e,o,t,Z,W,lr,h):
    delta_out= np.kron(np.kron(o,(1-o)),e)[0:3]
    print(delta_out)
    print(h.shape)
    Z=Z+np.dot(lr,np.dot(delta_out,np.transpose(h)))
    print(Z)
    delta_hidden=np.kron(np.kron(h,(1-h)),np.dot(np.transpose(Z),delta_out))[0:2]
    print(delta_hidden)
    W=W+np.dot(lr,np.dot(delta_hidden,np.transpose(X)))
    return(Z,W)

In [6]:
print(W.shape)

(2, 3)


In [7]:
print(X.shape)

(3, 1)


In [8]:
b,e,o,t,h=forward_propagation_1layer(X,W,Z,f,t)

Z,W=backpropagation_1layer(e,o,t,Z,W,lr,h)

(3, 1)
[[-0.11264174]
 [-0.08150109]
 [ 0.00039301]]
(2, 1)
[[0.09909641 0.19917652]
 [0.29934621 0.39940418]
 [0.50000315 0.60000287]]
[[-0.00561156]
 [-0.00868826]]
